### ISSUE TITLE
投掷/射击 攻击崩溃

### ISSUE THREAD

**Issue by al-wei** [ukmojb/SomeMods#1]
用投掷武器攻击崩溃（如果和武器有关，武器是更好的生存矛）。
https://mclo.gs/AsyURn5

**Comment by ukmojb** [comment]
你就tm没有匠魂盔甲为什么要加它??????????????????????????????????????

**Comment by al-wei** [comment]
之前有删了，但是就不能保留吗？我要得就是爆头为什么不能保留？难不成你这个还删了什么？
能不能好好说话？让我换旧版，或者你修改都行啊？

**Comment by al-wei** [comment]
而且兼容匠魂盔甲什么的。没有匠魂盔甲就必须崩溃吗？

**Comment by ukmojb** [comment]
有一种可能，我在介绍就说了修复匠魂盔甲的兼容，然后你不装，这和原版有什么区别

**Comment by al-wei** [comment]
有一种可能，你更应该挂上前置需求。兼容而不是需求前置，你自己都知道。这已经等于需求前置了。

**Comment by al-wei** [comment]
有一种可能，你更应该挂上前置需求。兼容而不是需求前置，你自己都知道。这已经等于需求前置了。你是添加功能，还是修改本质，要标明。

**Comment by al-wei** [comment]
没有就崩溃不是需求是什么。

**Comment by al-wei** [comment]
总之我，了解了，就是不会修改。我会停止使用这个mod。

**Comment by ukmojb** [comment]
不用了，为了你，我已经重新部署龙一遍环境

**Comment by ukmojb** [comment]
等一会吧

**Comment by al-wei** [comment]
做事知己知彼，外加一点严谨。你知到主页最后一句叫什么吗？剩余内容与原模组相同。崩溃怕是不算吧。不说别的我完全可以回退原模组，可以什么都不管直接拍屁股走人。但是早晚有一天会有人提出这个问题。必定有不用匠魂盔甲的人。比如我就是那个踩坑的人。可以说我也是为你而来。感谢你的贡献，祝你好运。

**Comment by ukmojb** [comment]
[iblis_headshots-0.6.4.zip](https://github.com/user-attachments/files/18138753/iblis_headshots-0.6.4.zip)
试试这个

**Comment by ukmojb** [comment]
> 做事知己知彼，外加一点严谨。你知到主页最后一句叫什么吗？剩余内容与原模组相同。崩溃怕是不算吧。不说别的我完全可以回退原模组，可以什么都不管直接拍屁股走人。但是早晚有一天会有人提出这个问题。必定有不用匠魂盔甲的人。比如我就是那个踩坑的人。可以说我也是为你而来。感谢你的贡献，祝你好运。

嗯

**Comment by al-wei** [comment]
我会严谨的测试它，再见。

**Comment by ukmojb** [comment]
不是，我在非玩家生物上用了null但不知道会不会崩溃,你先看看

**Comment by ukmojb** [comment]
用了保守一点的方法，你到仓库主页重新下载一下吧

**Comment by al-wei** [comment]
https://mclo.gs/4zEvLa3

**Comment by al-wei** [comment]
除此之外，无法攻击，你没想错，左键攻击没有任何反应那种。

**Comment by al-wei** [comment]
我决定使用原版，那并没有错误兼容更好的生存。并且还有curseforge我不需要为整合包设置mod-director。

**Comment by ukmojb** [comment]
getEntityId方法缺失????怎么可能???

**Comment by ukmojb** [comment]
这相当于你攻击了一个世界中不存在的生物

**Comment by al-wei** [comment]
我不知道怎么回事，我使用默认MC武器与生物测试得到的结果。

**Comment by ukmojb** [comment]
也许是我打包的问题?

**Comment by ukmojb** [comment]
毕竟我只加了个模组检测

**Comment by al-wei** [comment]
莫非改的过头了，改的正常变不正常，或者间接影响了，bug了。

**Comment by ukmojb** [comment]
[iblis_headshots-0.6.5.zip](https://github.com/user-attachments/files/18212390/iblis_headshots-0.6.5.zip)
不至于，我重新打包了一下

**Comment by ukmojb** [comment]
测试中弓箭正常爆头没出现问题

**Comment by al-wei** [comment]
![image](https://github.com/user-attachments/assets/c8338e75-01c9-4963-8a9d-be0a2aec02c6)

**Comment by al-wei** [comment]
图标黑咯

**Comment by al-wei** [comment]
![image](https://github.com/user-attachments/assets/1065fd72-0490-4775-bfe2-89899ed8af9c)
assets干没了，打包确实有问题了啊

**Comment by ukmojb** [comment]
啊，草，克隆的时候忘记资源了

**Comment by ukmojb** [comment]
[iblis_headshots-0.6.5.zip](https://github.com/user-attachments/files/18212526/iblis_headshots-0.6.5.zip)
理论没问题了

**Comment by al-wei** [comment]
![image](https://github.com/user-attachments/assets/8786e30a-0eb9-449d-aa94-28a306f04bf3)
你给我干沉默了

**Comment by ukmojb** [comment]
...我tm也沉默了

**Comment by al-wei** [comment]
![image](https://github.com/user-attachments/assets/33ed87b5-c803-40a9-ad27-fb439c305d2c)
这个也是不能配置了。

**Comment by al-wei** [comment]
而且我记得好像非射击类也可以爆头吧，但是我砍了半天了。都没看到爆头。

**Comment by ukmojb** [comment]
没有的,原本就有距离的判断,大于才能暴击

**Comment by al-wei** [comment]
哦那我记错了。我也是有段时间没玩了。

**Comment by ukmojb** [comment]
[iblis_headshots-0.6.5.zip](https://github.com/user-attachments/files/18212653/iblis_headshots-0.6.5.zip)

**Comment by ukmojb** [comment]
正常了

**Comment by ukmojb** [comment]
配置文件我是直接复制的

**Comment by al-wei** [comment]
配置还是那样

**Comment by ukmojb** [comment]
直接在文件改吧

**Comment by ukmojb** [comment]
睡了,人还有病

**Comment by ukmojb** [comment]
所以能用吗
